
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

[headers.values]
    X-Frame-Options = "Allow"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "https://frosty-leavitt-765165.netlify.app"
